version: '3.8'

services:
  service:
    build:
      context: ../..
      dockerfile: deployments/docker/Dockerfile
      args:
        NAME: go_app_service

    container_name: service
    restart: always
    ports:
      - "8080:8080"

  cli:
    build:
      context: ../..
      dockerfile: deployments/docker/cli/Dockerfile
      args:
        NAME: cli

    container_name: go_app_cli
    tty: true
    volumes:
      - ../..:/go/src/service

  mongo:
    build:
      context: ../..
      dockerfile: deployments/docker/mongo/Dockerfile
    container_name: go_app_mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_volume:/data/db

volumes:
  mongo_volume: