version: '3.8'

services:
  service:
    build:
      context: ../..
      dockerfile: deployments/docker/Dockerfile
      args:
        NAME: go_app_service

    container_name: service
    restart: always
    ports:
      - "8080:8080"

  cli:
    build:
      dockerfile: deployments/docker/cli/Dockerfile
      args:
        NAME: cli

    container_name: go_app_cli
    tty: true


