// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.18.1
// source: api/proto/campaign.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CampaignID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CampaignID) Reset() {
	*x = CampaignID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_campaign_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CampaignID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CampaignID) ProtoMessage() {}

func (x *CampaignID) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_campaign_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CampaignID.ProtoReflect.Descriptor instead.
func (*CampaignID) Descriptor() ([]byte, []int) {
	return file_api_proto_campaign_proto_rawDescGZIP(), []int{0}
}

func (x *CampaignID) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Campaign struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           *CampaignID  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name         string       `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AdvertiserId string       `protobuf:"bytes,3,opt,name=advertiserId,proto3" json:"advertiserId,omitempty"`
	SpentItems   []*SpentItem `protobuf:"bytes,17,rep,name=spentItems,proto3" json:"spentItems,omitempty"`
}

func (x *Campaign) Reset() {
	*x = Campaign{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_campaign_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Campaign) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Campaign) ProtoMessage() {}

func (x *Campaign) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_campaign_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Campaign.ProtoReflect.Descriptor instead.
func (*Campaign) Descriptor() ([]byte, []int) {
	return file_api_proto_campaign_proto_rawDescGZIP(), []int{1}
}

func (x *Campaign) GetId() *CampaignID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Campaign) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Campaign) GetAdvertiserId() string {
	if x != nil {
		return x.AdvertiserId
	}
	return ""
}

func (x *Campaign) GetSpentItems() []*SpentItem {
	if x != nil {
		return x.SpentItems
	}
	return nil
}

type SpentItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TotalSpent       int32   `protobuf:"varint,1,opt,name=totalSpent,proto3" json:"totalSpent,omitempty"`
	Cost             int32   `protobuf:"varint,2,opt,name=cost,proto3" json:"cost,omitempty"`
	Profit           int32   `protobuf:"varint,3,opt,name=profit,proto3" json:"profit,omitempty"`
	AgencyProfit     float32 `protobuf:"fixed32,4,opt,name=agencyProfit,proto3" json:"agencyProfit,omitempty"`
	Charge           float32 `protobuf:"fixed32,5,opt,name=charge,proto3" json:"charge,omitempty"`
	AdvertiserCharge float32 `protobuf:"fixed32,6,opt,name=advertiserCharge,proto3" json:"advertiserCharge,omitempty"`
	AgencyCharge     float32 `protobuf:"fixed32,8,opt,name=agencyCharge,proto3" json:"agencyCharge,omitempty"`
	TotalCost        int32   `protobuf:"varint,9,opt,name=totalCost,proto3" json:"totalCost,omitempty"`
}

func (x *SpentItem) Reset() {
	*x = SpentItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_campaign_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpentItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpentItem) ProtoMessage() {}

func (x *SpentItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_campaign_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpentItem.ProtoReflect.Descriptor instead.
func (*SpentItem) Descriptor() ([]byte, []int) {
	return file_api_proto_campaign_proto_rawDescGZIP(), []int{2}
}

func (x *SpentItem) GetTotalSpent() int32 {
	if x != nil {
		return x.TotalSpent
	}
	return 0
}

func (x *SpentItem) GetCost() int32 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *SpentItem) GetProfit() int32 {
	if x != nil {
		return x.Profit
	}
	return 0
}

func (x *SpentItem) GetAgencyProfit() float32 {
	if x != nil {
		return x.AgencyProfit
	}
	return 0
}

func (x *SpentItem) GetCharge() float32 {
	if x != nil {
		return x.Charge
	}
	return 0
}

func (x *SpentItem) GetAdvertiserCharge() float32 {
	if x != nil {
		return x.AdvertiserCharge
	}
	return 0
}

func (x *SpentItem) GetAgencyCharge() float32 {
	if x != nil {
		return x.AgencyCharge
	}
	return 0
}

func (x *SpentItem) GetTotalCost() int32 {
	if x != nil {
		return x.TotalCost
	}
	return 0
}

var File_api_proto_campaign_proto protoreflect.FileDescriptor

var file_api_proto_campaign_proto_rawDesc = []byte{
	0x0a, 0x18, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x61, 0x6d, 0x70,
	0x61, 0x69, 0x67, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x62, 0x6c, 0x61, 0x6e,
	0x6b, 0x22, 0x1c, 0x0a, 0x0a, 0x43, 0x61, 0x6d, 0x70, 0x61, 0x69, 0x67, 0x6e, 0x49, 0x44, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x97, 0x01, 0x0a, 0x08, 0x43, 0x61, 0x6d, 0x70, 0x61, 0x69, 0x67, 0x6e, 0x12, 0x21, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x62, 0x6c, 0x61, 0x6e, 0x6b,
	0x2e, 0x43, 0x61, 0x6d, 0x70, 0x61, 0x69, 0x67, 0x6e, 0x49, 0x44, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x61, 0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x61, 0x64, 0x76, 0x65, 0x72,
	0x74, 0x69, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x30, 0x0a, 0x0a, 0x73, 0x70, 0x65, 0x6e, 0x74,
	0x49, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x11, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x62, 0x6c,
	0x61, 0x6e, 0x6b, 0x2e, 0x53, 0x70, 0x65, 0x6e, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x0a, 0x73,
	0x70, 0x65, 0x6e, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x81, 0x02, 0x0a, 0x09, 0x53, 0x70,
	0x65, 0x6e, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x53, 0x70, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x53, 0x70, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x73, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x70,
	0x72, 0x6f, 0x66, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x70, 0x72, 0x6f,
	0x66, 0x69, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x61, 0x67, 0x65, 0x6e, 0x63, 0x79, 0x50, 0x72, 0x6f,
	0x66, 0x69, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0c, 0x61, 0x67, 0x65, 0x6e, 0x63,
	0x79, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x68, 0x61, 0x72, 0x67,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x63, 0x68, 0x61, 0x72, 0x67, 0x65, 0x12,
	0x2a, 0x0a, 0x10, 0x61, 0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x72, 0x43, 0x68, 0x61,
	0x72, 0x67, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x02, 0x52, 0x10, 0x61, 0x64, 0x76, 0x65, 0x72,
	0x74, 0x69, 0x73, 0x65, 0x72, 0x43, 0x68, 0x61, 0x72, 0x67, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x61,
	0x67, 0x65, 0x6e, 0x63, 0x79, 0x43, 0x68, 0x61, 0x72, 0x67, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x0c, 0x61, 0x67, 0x65, 0x6e, 0x63, 0x79, 0x43, 0x68, 0x61, 0x72, 0x67, 0x65, 0x12,
	0x1c, 0x0a, 0x09, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x43, 0x6f, 0x73, 0x74, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x09, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x43, 0x6f, 0x73, 0x74, 0x42, 0x1d, 0x5a,
	0x1b, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x65, 0x73, 0x65, 0x6e,
	0x74, 0x65, 0x72, 0x73, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_proto_campaign_proto_rawDescOnce sync.Once
	file_api_proto_campaign_proto_rawDescData = file_api_proto_campaign_proto_rawDesc
)

func file_api_proto_campaign_proto_rawDescGZIP() []byte {
	file_api_proto_campaign_proto_rawDescOnce.Do(func() {
		file_api_proto_campaign_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_campaign_proto_rawDescData)
	})
	return file_api_proto_campaign_proto_rawDescData
}

var file_api_proto_campaign_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_proto_campaign_proto_goTypes = []interface{}{
	(*CampaignID)(nil), // 0: blank.CampaignID
	(*Campaign)(nil),   // 1: blank.Campaign
	(*SpentItem)(nil),  // 2: blank.SpentItem
}
var file_api_proto_campaign_proto_depIdxs = []int32{
	0, // 0: blank.Campaign.id:type_name -> blank.CampaignID
	2, // 1: blank.Campaign.spentItems:type_name -> blank.SpentItem
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_proto_campaign_proto_init() }
func file_api_proto_campaign_proto_init() {
	if File_api_proto_campaign_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_proto_campaign_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CampaignID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_campaign_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Campaign); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_campaign_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpentItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_campaign_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_campaign_proto_goTypes,
		DependencyIndexes: file_api_proto_campaign_proto_depIdxs,
		MessageInfos:      file_api_proto_campaign_proto_msgTypes,
	}.Build()
	File_api_proto_campaign_proto = out.File
	file_api_proto_campaign_proto_rawDesc = nil
	file_api_proto_campaign_proto_goTypes = nil
	file_api_proto_campaign_proto_depIdxs = nil
}
