// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.18.1
// source: api/proto/service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_api_proto_service_proto protoreflect.FileDescriptor

var file_api_proto_service_proto_rawDesc = []byte{
	0x0a, 0x17, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x62, 0x6c, 0x61, 0x6e, 0x6b,
	0x1a, 0x18, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x61, 0x6d, 0x70,
	0x61, 0x69, 0x67, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1a, 0x61, 0x70, 0x69, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x72,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x32, 0xcd, 0x01, 0x0a, 0x10, 0x50, 0x6c, 0x61, 0x74, 0x66,
	0x6f, 0x72, 0x6d, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3d, 0x0a, 0x0e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x61, 0x6d, 0x70, 0x61, 0x69, 0x67, 0x6e, 0x12, 0x16, 0x2e,
	0x62, 0x6c, 0x61, 0x6e, 0x6b, 0x2e, 0x43, 0x61, 0x6d, 0x70, 0x61, 0x69, 0x67, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x62, 0x6c, 0x61, 0x6e, 0x6b, 0x2e, 0x43, 0x61,
	0x6d, 0x70, 0x61, 0x69, 0x67, 0x6e, 0x49, 0x44, 0x22, 0x00, 0x12, 0x3c, 0x0a, 0x0c, 0x46, 0x69,
	0x6e, 0x64, 0x43, 0x61, 0x6d, 0x70, 0x61, 0x69, 0x67, 0x6e, 0x12, 0x11, 0x2e, 0x62, 0x6c, 0x61,
	0x6e, 0x6b, 0x2e, 0x43, 0x61, 0x6d, 0x70, 0x61, 0x69, 0x67, 0x6e, 0x49, 0x44, 0x1a, 0x17, 0x2e,
	0x62, 0x6c, 0x61, 0x6e, 0x6b, 0x2e, 0x43, 0x61, 0x6d, 0x70, 0x61, 0x69, 0x67, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3c, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x41, 0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x72, 0x12, 0x11, 0x2e, 0x62,
	0x6c, 0x61, 0x6e, 0x6b, 0x2e, 0x41, 0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x72, 0x1a,
	0x13, 0x2e, 0x62, 0x6c, 0x61, 0x6e, 0x6b, 0x2e, 0x41, 0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73,
	0x65, 0x72, 0x49, 0x44, 0x22, 0x00, 0x42, 0x1d, 0x5a, 0x1b, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x2f, 0x70, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x73, 0x2f, 0x67, 0x72,
	0x70, 0x63, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var file_api_proto_service_proto_goTypes = []interface{}{
	(*CampaignRequest)(nil),  // 0: blank.CampaignRequest
	(*CampaignID)(nil),       // 1: blank.CampaignID
	(*Advertiser)(nil),       // 2: blank.Advertiser
	(*CampaignResponse)(nil), // 3: blank.CampaignResponse
	(*AdvertiserID)(nil),     // 4: blank.AdvertiserID
}
var file_api_proto_service_proto_depIdxs = []int32{
	0, // 0: blank.PlatformsService.CreateCampaign:input_type -> blank.CampaignRequest
	1, // 1: blank.PlatformsService.FindCampaign:input_type -> blank.CampaignID
	2, // 2: blank.PlatformsService.CreateAdvertiser:input_type -> blank.Advertiser
	1, // 3: blank.PlatformsService.CreateCampaign:output_type -> blank.CampaignID
	3, // 4: blank.PlatformsService.FindCampaign:output_type -> blank.CampaignResponse
	4, // 5: blank.PlatformsService.CreateAdvertiser:output_type -> blank.AdvertiserID
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_service_proto_init() }
func file_api_proto_service_proto_init() {
	if File_api_proto_service_proto != nil {
		return
	}
	file_api_proto_campaign_proto_init()
	file_api_proto_advertiser_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_service_proto_goTypes,
		DependencyIndexes: file_api_proto_service_proto_depIdxs,
	}.Build()
	File_api_proto_service_proto = out.File
	file_api_proto_service_proto_rawDesc = nil
	file_api_proto_service_proto_goTypes = nil
	file_api_proto_service_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PlatformsServiceClient is the client API for PlatformsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PlatformsServiceClient interface {
	CreateCampaign(ctx context.Context, in *CampaignRequest, opts ...grpc.CallOption) (*CampaignID, error)
	FindCampaign(ctx context.Context, in *CampaignID, opts ...grpc.CallOption) (*CampaignResponse, error)
	CreateAdvertiser(ctx context.Context, in *Advertiser, opts ...grpc.CallOption) (*AdvertiserID, error)
}

type platformsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPlatformsServiceClient(cc grpc.ClientConnInterface) PlatformsServiceClient {
	return &platformsServiceClient{cc}
}

func (c *platformsServiceClient) CreateCampaign(ctx context.Context, in *CampaignRequest, opts ...grpc.CallOption) (*CampaignID, error) {
	out := new(CampaignID)
	err := c.cc.Invoke(ctx, "/blank.PlatformsService/CreateCampaign", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformsServiceClient) FindCampaign(ctx context.Context, in *CampaignID, opts ...grpc.CallOption) (*CampaignResponse, error) {
	out := new(CampaignResponse)
	err := c.cc.Invoke(ctx, "/blank.PlatformsService/FindCampaign", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformsServiceClient) CreateAdvertiser(ctx context.Context, in *Advertiser, opts ...grpc.CallOption) (*AdvertiserID, error) {
	out := new(AdvertiserID)
	err := c.cc.Invoke(ctx, "/blank.PlatformsService/CreateAdvertiser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlatformsServiceServer is the server API for PlatformsService service.
type PlatformsServiceServer interface {
	CreateCampaign(context.Context, *CampaignRequest) (*CampaignID, error)
	FindCampaign(context.Context, *CampaignID) (*CampaignResponse, error)
	CreateAdvertiser(context.Context, *Advertiser) (*AdvertiserID, error)
}

// UnimplementedPlatformsServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPlatformsServiceServer struct {
}

func (*UnimplementedPlatformsServiceServer) CreateCampaign(context.Context, *CampaignRequest) (*CampaignID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCampaign not implemented")
}
func (*UnimplementedPlatformsServiceServer) FindCampaign(context.Context, *CampaignID) (*CampaignResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindCampaign not implemented")
}
func (*UnimplementedPlatformsServiceServer) CreateAdvertiser(context.Context, *Advertiser) (*AdvertiserID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAdvertiser not implemented")
}

func RegisterPlatformsServiceServer(s *grpc.Server, srv PlatformsServiceServer) {
	s.RegisterService(&_PlatformsService_serviceDesc, srv)
}

func _PlatformsService_CreateCampaign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CampaignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformsServiceServer).CreateCampaign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blank.PlatformsService/CreateCampaign",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformsServiceServer).CreateCampaign(ctx, req.(*CampaignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformsService_FindCampaign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CampaignID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformsServiceServer).FindCampaign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blank.PlatformsService/FindCampaign",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformsServiceServer).FindCampaign(ctx, req.(*CampaignID))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformsService_CreateAdvertiser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Advertiser)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformsServiceServer).CreateAdvertiser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blank.PlatformsService/CreateAdvertiser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformsServiceServer).CreateAdvertiser(ctx, req.(*Advertiser))
	}
	return interceptor(ctx, in, info, handler)
}

var _PlatformsService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "blank.PlatformsService",
	HandlerType: (*PlatformsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCampaign",
			Handler:    _PlatformsService_CreateCampaign_Handler,
		},
		{
			MethodName: "FindCampaign",
			Handler:    _PlatformsService_FindCampaign_Handler,
		},
		{
			MethodName: "CreateAdvertiser",
			Handler:    _PlatformsService_CreateAdvertiser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/service.proto",
}
